apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: default
spec:
  override:
    statefulSet:
      spec:
        template:
          metadata:
            labels:
              app: rabbitmq
  replicas: 1
  rabbitmq:
    additionalConfig: |
      default_user = admin
      default_pass = adminadminadmin
  service:
    type: NodePort
