external_services:
  redis_server:
    host: 195.148.22.62
    port: 6379
    db: 0

  service_registry:
    consul_config:
      url: http://195.148.22.62:8500

qoa_config:
  client:
    user_id: aaltosea2
    instance_id: image_info_service_01
    stage_id: ImageInfo
    functionality: REST
    application_name: nii
    role: ml
  connector:
    - name: amqp_connector
      connector_class: AMQP
      config:
        end_point: 195.148.22.62
        exchange_name: nii_inference
        exchange_type: topic
        out_routing_key: nii.imageinfo
  registration_url: http://0.0.0.0:5010/registration
