apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  default.server: |
    cloud-1.svc:53 {
        hosts {
            <ip> gateway.cloud-1.svc
            fallthrough
        }
    }
