---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efficientnetb0
  labels:
    app: efficientnetb0
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efficientnetb0
      version: v1
  template:
    metadata:
      labels:
        app: efficientnetb0
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      runtimeClassName: nvidia
      containers:
        - name: efficientnetb0
          imagePullPolicy: "IfNotPresent"
          image: rdsea/inference_gpu:latest
          ports:
            - containerPort: 5012
          args: ["--model", "EfficientNetB0"]
          env:
            - name: MANUAL_TRACING
              value: "false"
            - name: OTEL_ENDPOINT
              value: "http://my-opentelemetry-collector.observe:4318/v1/traces"
---
apiVersion: v1
kind: Service
metadata:
  name: efficientnetb0-service
spec:
  ports:
    - port: 5012
      targetPort: 5012
  selector:
    app: efficientnetb0
