---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ensemble
  labels:
    app: ensemble
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ensemble
      version: v1
  template:
    metadata:
      labels:
        app: ensemble
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "true"
      containers:
        - name: ensemble
          imagePullPolicy: "Always"
          image: rdsea/ensemble
          ports:
            - containerPort: 5011
          env:
            - name: LOG_LEVEL
              value: "WARNING"
            - name: MANUAL_TRACING
              value: "true"
            - name: OTEL_ENDPOINT
              value: "http://my-opentelemetry-collector.observe:4318/v1/traces"
            - name: SEND_TO_QUEUE
              value: "true"
            - name: RABBITMQ_URL
              value: "gateway.cloud-1.svc:30072"
            - name: RABBITMQ_QUEUE_NAME
              value: "object_detection_result"
            - name: RABBITMQ_USERNAME
              value: "admin"
            - name: RABBITMQ_PASSWORD
              value: "adminadminadmin"
          resources:
            requests:
              cpu: "250m"
              memory: "200Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ensemble-service
spec:
  ports:
    - port: 5011
      targetPort: 5011
  selector:
    app: ensemble
