version: "3.8"

services:
  consul:
    image: hashicorp/consul:latest
    container_name: consul
    network_mode: host
    # ports:
    #   - "8500:8500"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    network_mode: host
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"
  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
