loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  auth_enabled: false

gateway:
  service:
    annotations:
      io.cilium/global-service: "true"

minio:
  enabled: true
  rootUser: root-user
  rootPassword: supersecretpassword
  serviceAccount:
    name: tempo-minio-sa
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
  persistence:
    size: 10Gi
    storageClass: longhorn

# Zero out replica counts of other deployment modes
test:
  enabled: false
lokiCanary:
  enabled: false

chunksCache:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
