FROM flink:1.20.2-java17

# install python3 and pip3
RUN apt-get update -y && \
  apt-get install -y python3 python3-pip python3-dev && \
  rm -rf /var/lib/apt/lists/*

# install PyFlink
RUN pip3 install apache-flink==1.20.2
