apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-kafka-adapter-node
  labels:
    app: prom-kafka-adapter-node
  namespace: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-kafka-adapter-node
  template:
    metadata:
      labels:
        app: prom-kafka-adapter-node
    spec:
      containers:
        - name: adapter
          image: telefonica/prometheus-kafka-adapter:1.9.1
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER_LIST
              value: "redpanda-0.redpanda.redpanda.svc.cluster.local:9093, redpanda-1.redpanda.redpanda.svc.cluster.local:9093, redpanda-2.redpanda.redpanda.svc.cluster.local:9093"
            - name: KAFKA_TOPIC
              value: "node_metric"
            - name: MATCH
              value: '[ "node:cpu_usage", "node:memory_usage_percentage", "node:disk_read", "node:disk_written", "node:disk_io_time", "node:network_receive", "node:network_transmit", ]'
            - name: LOG_LEVEL
              value: "info"
            - name: KAFKA_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: KAFKA_SASL_MECHANISM
              value: "PLAIN"
            - name: KAFKA_SASL_USERNAME
              value: "alice"
            - name: KAFKA_SASL_PASSWORD
              value: "redpanda"
            - name: KAFKA_SSL_CA_CERT_FILE
              value: "/etc/tls/certs/ca.crt"
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/tls/certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: redpanda-default-cert
---
apiVersion: v1
kind: Service
metadata:
  name: prom-kafka-adapter-node
  namespace: redpanda
spec:
  selector:
    app: prom-kafka-adapter-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
