apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-ipaddresspool
  namespace: metallb-system
spec:
  addresses:
    # For k3s
    # - 172.18.255.200-172.18.255.250
    # For minikube
    - 192.168.49.2-192.168.49.255
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb-system
