---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing
  labels:
    app: preprocessing
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessing
      version: v1
  template:
    metadata:
      labels:
        app: preprocessing
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: preprocessing
          imagePullPolicy: "IfNotPresent"
          image: rdsea/preprocessing
          ports:
            - containerPort: 5010
          env:
            - name: MANUAL_TRACING
              value: "true"
            - name: OTEL_ENDPOINT
              value: "http://my-opentelemetry-collector.default:4318/v1/traces"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: preprocessing-service
spec:
  ports:
    - port: 5010
      targetPort: 5010
  selector:
    app: preprocessing
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: preprocessing-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: preprocessing
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
