FROM debian:stable-slim

RUN apt update

RUN apt install curl gpg -y

RUN curl -sSLf https://get.openziti.io/tun/package-repos.gpg | gpg --dearmor --output /usr/share/keyrings/openziti.gpg

RUN chmod -c +r /usr/share/keyrings/openziti.gpg

RUN echo "deb [signed-by=/usr/share/keyrings/openziti.gpg] https://packages.openziti.org/zitipax-openziti-deb-stable jammy main" | tee /etc/apt/sources.list.d/openziti.list >/dev/null

RUN apt update

RUN apt install -y ziti-edge-tunnel

WORKDIR /ensemble

COPY --from=ghcr.io/astral-sh/uv:0.4.3 /uv /bin/uv

COPY ./ensemble/*.toml ./

COPY ./ensemble/run_server.sh ./ensemble/run_server.sh

COPY ./ensemble/ziti_start.sh ./ensemble/ziti_start.sh

RUN uv sync --compile-bytecode --no-cache

COPY ./ensemble/*.py ./ensemble/

COPY ./ensemble/*.yaml ./ensemble/

COPY ./util/ ./util

EXPOSE 5011

WORKDIR /ensemble/ensemble

ENV PATH="/ensemble/.venv/bin:$PATH"

ENTRYPOINT [ "./ziti_start.sh" ]
