version: "3.8"

services:
  preprocessing:
    image: rdsea/preprocessing:v1
    container_name: preprocessing
    networks:
      - host

  ensemble:
    image: rdsea/object_classification_ensemble:v1
    container_name: ensemble
    networks:
      - host

  inference_cpu_mobilenet:
    image: rdsea/onnx_inference:cpu
    container_name: inference_cpu_mobilenet
    networks:
      - host

  inference_cpu_efficientnet:
    image: rdsea/onnx_inference:cpu
    container_name: inference_cpu_efficientnet
    command: ["--model", "EfficientNetB0"]
    networks:
      - host

networks:
  host:
    external: true
