apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ensemble-to-efficientnetb0
spec:
  endpointSelector:
    matchLabels:
      app: efficientnetb0-service
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: ensemble-service
    - toPorts:
        - ports:
            - port: "5012"
              protocol: TCP
